name: build-test

on:
  push:
    branches:
      - "main"
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Write dotenv file
        run: |
          cat <<-EOF >.env
          VITE_GIT_COMMIT=${GITHUB_SHA}
          VITE_ROBOTS_INDEX_ALL=${{ github.event_name == 'release' }}
          EOF
      - run: npm ci
      - run: npm run build

      - name: Write version file
        run: |
          # write version info to artifact
          echo "Built from GitHub repo ${{ github.repository }} version ${GITHUB_SHA::7}" > ./build/version.txt

      # add some tests here
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: ./build/
          retention-days: 1
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    # Run on main branch, release or if PR contains the 'preview' label
    if: github.ref == 'refs/heads/main' || github.event_name == 'release' || contains( github.event.pull_request.labels.*.name, 'preview')

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website
          path: ./website
      - name: Write deploy variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "release" ]
          then
            echo "deploy_env=prod" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF#refs/heads/}" == "main" ]
          then
            echo "deploy_env=staging" >> $GITHUB_OUTPUT
          elif [ "${{ contains( github.event.pull_request.labels.*.name, 'preview') }}" == "true" ]
          then
            echo "deploy_env=preview" >> $GITHUB_OUTPUT
          else
            echo "deploy_env=unknown" >> $GITHUB_OUTPUT
          fi
      - name: Dump deployment variables
        run: echo "${{ steps.vars.outputs.deploy_env }}"
      - name: Upload to google storage
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: verifa-website
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          cli: gsutil
          args: "-m rsync -r -c -d ./website gs://website-bucket-${{ steps.vars.outputs.deploy_env }}"
      # Set no-store cache-control for all objects by default
      - name: Set cache-control no-store
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: verifa-website
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          cli: gsutil
          args: |
            -m setmeta -h 'Cache-Control: no-store' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.*'"
      # Set public cache-control for specific file extensions
      - name: Set cache-control public
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: verifa-website
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          cli: gsutil
          args: |
            -m setmeta -h 'Cache-Control: public,max-age=31536000' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.css' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.ico' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.jpg' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.js' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.png' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.svg' \
              'gs://website-bucket-${{ steps.vars.outputs.deploy_env }}/**.ttf'
